### ISSUE TITLE
support for autogenerating text/ascii notifications

### ISSUE THREAD

**Issue by george-silva** [worthwhile/django-herald#42] opened 2018-01-05 00:48 UTC
Hello everyone! Great project!

I'm using it in production for one our SaaS and it's working nicely.

One of the things I've just learned about today is https://pypi.python.org/pypi/html2text.

There is a big hassle in creating and maintaining two sets of templates, one for html and one for txt. Perhps we could integrate with html2text and auto-generate the text emails, when the txt template is not available?

I can contribute, but I would like to know how you feel about that, before starting it.

**Comment by jproffitt** [comment] 2018-01-05 00:56
I think that would be a great feature! The issue is sometimes the auto generated version is not very pretty. But I think that it would be nice to default to the auto generated version if no text template exists.

**Comment by george-silva** [comment] 2018-01-05 00:59
I mean, for the most part, it will probably be ok.

There's one caveat designing the plain text emails regarding the use of django tags, like `for` and `ifs`. If you keep breaking lines, for easy modification/understading, they will show up on the plain email, which is a pain to modify, leading to very long lines inside your template...

Well, I'll start cracking on this sometime next week or so. It will save me more time to implement this instead of designing two sets of emails. Great :D

**Comment by raiderrobert** [comment] 2018-01-05 01:00
@george-silva thanks so much! I've assigned this over to you!

**Comment by peterfarrell** [comment] 2020-07-17 21:34
We implemented this at work and could share back. It uses `html2text` if people are ok with adding that as a dependency.  I'd be happy to make a PR.

**Comment by raiderrobert** [comment] 2020-07-17 21:41
@peterfarrell feel free. Add it into the `extras_require` section

**Comment by peterfarrell** [comment] 2020-07-20 14:04
@raiderrobert Working on a PR this week including updates to docs and tests.

**Comment by peterfarrell** [comment] 2020-08-14 20:08
@raiderrobert PR in #68

**Closed** 2020-08-17 12:26 UTC
Labels: enhancement
